import MainNavigation from "@/src/components/layout/MainNavigation";
import "./globals.css";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Meetups",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <MainNavigation />
        <main className={styles.main}>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </main>
      </body>
    </html>
  );
}
